### ISSUE TITLE
Consider removing JSS in favour of pure ClojureScript

### ISSUE THREAD

**Issue by axrs** [axrs/re-css#6]
For distribution simplicity, it would be nice to completely remove the dependency tie to JSS. It should be possible to leverage `js/document` capabilities to achieve the same result.

## Ideal Examples:

```clojure
{:button {:background "red"
                "loading" {:background "green"}}
```
```css
.button-1 {background: "red";}  // :button gets a unique class name
.button-1 .loading {background: "green";} // loading is preserved as it's a string
```

```clojure
{:button {:background "red"
                :& {"loading" {:background "green"}}}}
```
```css
.button-1 {background: "red";}  // :button gets a unique class name
.button-1.loading {background: "green";} // loading is preserved and joined to :button
```

## Try to support
* Generated class names with style reuse when identical
* Automatic vendor prefixing
* Nested styles
* Auto prefixing (`px`, `em`, `rem`) some values
* Keyword to string `{:pointer-events :none}` -> `{pointer-events: "none"}`
* nested map type for css overloads
** `{:padding {:left 0 :right 0}}` -> `{padding-left: 0; padding-right: 0}`
